export const ADD_FRIENDS = 'ADD_FRIENDS';
export const FRIENDS_LOADING = 'FRIENDS_LOADING';
export const FRIENDS_FAILED = 'FRIENDS_FAILED';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const REQUESTS_LOADING = 'REQUESTS_LOADING';
export const REQUESTS_FAILED = 'REQUESTS_FAILED';
export const ADD_REQUESTS = 'ADD_REQUESTS';

export const USERS_LOADING = 'USERS_LOADING';
export const USERS_FAILED = 'USERS_FAILED';
export const ADD_USERS = 'ADD_USERS';

export const ACCOUNT_LOADING = 'ACCOUNT_LOADING';
export const ACCOUNT_FAILED = 'ACCOUNT_FAILED';
export const ADD_ACCOUNT = 'ADD_ACCOUNT';

export const ADD_FRIENDS_COORDS = 'ADD_FRIENDS_COORDS';
export const FRIENDS_COORDS_LOADING = 'FRIENDS_COORDS_LOADING';
export const FRIENDS_COORDS_FAILED = 'FRIENDS_COORDS_FAILED';